# Generated by Django 5.1.1 on 2024-10-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='single',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
