# Generated by Django 5.1.1 on 2024-10-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single', '0002_single_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='single',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
