# Generated by Django 5.1.1 on 2024-10-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single', '0003_single_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='single',
            name='slug',
            field=models.SlugField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
