# Generated by Django 5.1 on 2024-10-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('type', models.CharField(max_length=125)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.IntegerField()),
                ('last_price', models.IntegerField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=125, null=True)),
            ],
            options={
                'verbose_name': 'offering',
                'verbose_name_plural': 'offerings',
            },
        ),
    ]
