# Generated by Django 5.1.1 on 2024-10-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='Best_Seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offering',
            name='New_Arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offering',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
