# Generated by Django 5.1.1 on 2024-10-05 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offering', '0002_offering_best_seller_offering_new_arrival_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offering',
            old_name='Best_Seller',
            new_name='best_seller',
        ),
        migrations.RenameField(
            model_name='offering',
            old_name='New_Arrival',
            new_name='new_arrival',
        ),
    ]
