# Generated by Django 5.1.1 on 2024-10-08 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('type', models.CharField(max_length=125)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d')),
                ('price', models.IntegerField()),
                ('last_price', models.IntegerField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=125, null=True)),
                ('best_seller', models.BooleanField(default=False)),
                ('new_arrival', models.BooleanField(default=False)),
                ('on_sale', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='store.category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.DeleteModel(
            name='Porduct',
        ),
    ]
