# Generated by Django 5.1 on 2024-10-02 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiense',
            options={'verbose_name': 'Experiense', 'verbose_name_plural': 'Experienses'},
        ),
    ]
