# Generated by Django 5.1 on 2024-10-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0002_alter_experiense_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiense',
            name='number',
            field=models.IntegerField(),
        ),
    ]
