# Generated by Django 5.1.1 on 2024-10-16 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0004_comment_comment_image_alter_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_image',
        ),
    ]
