# Generated by Django 5.1 on 2024-10-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('content', models.CharField(max_length=225)),
                ('icons', models.CharField(blank=True, max_length=125, null=True)),
            ],
            options={
                'verbose_name': 'support',
                'verbose_name_plural': 'supports',
            },
        ),
    ]
