# Generated by Django 5.1.1 on 2024-10-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_checkout_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
