# Generated by Django 5.1.1 on 2024-10-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_checkout_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='product_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
