# Generated by Django 5.1.1 on 2024-10-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_remove_checkout_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='product_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='product_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
