# Generated by Django 5.1 on 2024-10-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('content', models.CharField(max_length=125)),
                ('address', models.ImageField(blank=True, null=True, upload_to='')),
                ('phone', models.IntegerField(null=True)),
                ('telegram', models.CharField(blank=True, max_length=125, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, max_length=125, null=True)),
                ('discord', models.URLField(blank=True, max_length=125, null=True)),
            ],
            options={
                'verbose_name': 'Info',
                'verbose_name_plural': 'Infos',
            },
        ),
    ]
