# Generated by Django 5.1.1 on 2024-10-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
